version: "3.9"

services:
  db:
    image: postgres:15
    container_name: palpites-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  db_test:
    image: postgres:15
    container_name: palpites-db-test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: palpites-backend
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT}:3000"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
  postgres_data_test: